name: dummy_workflow 

# github event 
# since this github event is workflow_dispatch it needs to be manually triggered 
on: 
  workflow_dispatch:

# this is the jobs and which has steps on what to run 
# here dummy_task is a job and it has its own steps 
jobs:
  # Job 1
  dummy_task_in_shell:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dummy workflow"

  # Job 2
  dummy_task_in_python:
    runs-on: ubuntu-latest
    steps:
      - run: print("This is the dummy task in python")
        shell: python
  
  # Job 3
  dummy_task_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "dummy task using actions "

