name: dummy_workflow 

# github event
on: 
  workflow_dispatch:

# this is the jobs and which has steps on what to run 
# here dummy_task is a job and it has its own steps 
jobs:
  dummy_task:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dummy workflow"